/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BillingForm.java
 *
 * Created on Nov 14, 2012, 7:21:23 AM
 */
package pharmacuticals_billing_systema;

import Model.InventoryModel;
import Model.SalesModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;

/**
 *
 * @author paradise lost
 */
public class BillingForm extends javax.swing.JPanel implements Printable{

    /** Creates new form BillingForm */
    public BillingForm() {
        initComponents();
        this.setSize(1210,710);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerNameField = new javax.swing.JTextField();
        customerLocationField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cashReceivedField = new javax.swing.JTextField();
        upqLabel = new javax.swing.JLabel();
        changeLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        particularField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        rateField = new javax.swing.JTextField();
        amountField = new javax.swing.JTextField();
        quantityBox = new java.awt.Choice();
        rateBox = new java.awt.Choice();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ParticularList = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        quantityList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        amountList = new javax.swing.JList();
        pushButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        Product1 = new javax.swing.JLabel();
        Product2 = new javax.swing.JLabel();
        Product3 = new javax.swing.JLabel();
        Product4 = new javax.swing.JLabel();
        Product5 = new javax.swing.JLabel();
        Product6 = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        automaticRadioButton = new javax.swing.JRadioButton();
        Product7 = new javax.swing.JLabel();
        Product8 = new javax.swing.JLabel();
        Product9 = new javax.swing.JLabel();
        successLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        rateList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        billNo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 18), new java.awt.Dimension(0, 18), new java.awt.Dimension(32767, 18));
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        disButton = new javax.swing.JRadioButton();
        disField = new javax.swing.JTextField();
        percentField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        itemSelector = new javax.swing.JSpinner();
        DeleteRadio = new javax.swing.JRadioButton();
        EditRadio = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerNameField.setFont(new java.awt.Font("Tahoma", 0, 14));
        customerNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExited(evt);
            }
        });
        customerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameFieldActionPerformed(evt);
            }
        });
        customerNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNameFieldFocusLost(evt);
            }
        });
        customerNameField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TextChanged(evt);
            }
        });
        customerNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customerNameFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTypedHandeler(evt);
            }
        });
        customerNameField.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                TextValuechanged(evt);
            }
        });
        add(customerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 240, 30));

        customerLocationField.setFont(new java.awt.Font("Tahoma", 0, 14));
        customerLocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerLocationFieldActionPerformed(evt);
            }
        });
        add(customerLocationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 240, 30));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Name of Customer");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, 36));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Place of Stay ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, 36));

        dateField.setFont(new java.awt.Font("Tahoma", 0, 14));
        dateField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DateMouseExited(evt);
            }
        });
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });
        dateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateFieldFocusLost(evt);
            }
        });
        dateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyTypedForDate(evt);
            }
        });
        add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 240, 30));
        SimpleDateFormat d = new SimpleDateFormat("yyyy/MM/dd");
        dateField.setText(d.format(new Date()));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Date ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, 36));

        cashReceivedField.setFont(new java.awt.Font("Tahoma", 0, 14));
        cashReceivedField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CashReceivedMouseExited(evt);
            }
        });
        cashReceivedField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cashReceivedFieldFocusLost(evt);
            }
        });
        cashReceivedField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cashReceivedFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CashReceivedKeyTyped(evt);
            }
        });
        add(cashReceivedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 130, 30));

        upqLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
        upqLabel.setForeground(new java.awt.Color(0, 51, 204));
        upqLabel.setText("Discount         NRS             % Percent");
        add(upqLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 270, 20));

        changeLabel.setBackground(new java.awt.Color(204, 204, 255));
        changeLabel.setFont(new java.awt.Font("Calibri", 0, 24));
        changeLabel.setText("00.00 NRS");
        add(changeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 190, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Rate");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 60, 20));

        particularField.setFont(new java.awt.Font("Tahoma", 0, 14));
        particularField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ParticularMouseExited(evt);
            }
        });
        particularField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                particularFieldActionPerformed(evt);
            }
        });
        particularField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                particularFieldFocusLost(evt);
            }
        });
        particularField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                particularFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                particularKeyTyped(evt);
            }
        });
        add(particularField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 260, 30));

        quantityField.setFont(new java.awt.Font("Tahoma", 0, 14));
        quantityField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuantityMouseExited(evt);
            }
        });
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });
        quantityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityFieldFocusLost(evt);
            }
        });
        quantityField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityKeyTyped(evt);
            }
        });
        add(quantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 60, 30));

        rateField.setFont(new java.awt.Font("Tahoma", 0, 14));
        rateField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RateMouseExited(evt);
            }
        });
        rateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateFieldActionPerformed(evt);
            }
        });
        rateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rateFieldFocusLost(evt);
            }
        });
        rateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rateFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RateKeyTyped(evt);
            }
        });
        add(rateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 60, 30));

        amountField.setFont(new java.awt.Font("Tahoma", 0, 14));
        amountField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AmountMouseExited(evt);
            }
        });
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        amountField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountFieldFocusLost(evt);
            }
        });
        amountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AmountKeyTyped(evt);
            }
        });
        add(amountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 80, 30));

        quantityBox.setFont(new java.awt.Font("Tahoma", 0, 14));
        add(quantityBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 60, 20));
        quantityBox.add("tablets");
        quantityBox.add("grams");
        quantityBox.add("ml");

        rateBox.setFont(new java.awt.Font("Tahoma", 0, 14));
        add(rateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 60, -1));
        rateBox.add("Integral");
        rateBox.add("/tablet");
        rateBox.add("/mg");
        rateBox.add("/ml");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel13.setForeground(new java.awt.Color(0, 51, 204));
        jLabel13.setText("Particulars");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 140, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel14.setForeground(new java.awt.Color(0, 51, 204));
        jLabel14.setText("Quantity");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 90, 20));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 5));

        ParticularList.setBackground(new java.awt.Color(204, 204, 204));
        ParticularList.setFont(new java.awt.Font("Segoe UI", 0, 10));
        ParticularList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ParticularList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 390, 10));

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 5));

        quantityList.setBackground(new java.awt.Color(204, 204, 204));
        quantityList.setFont(new java.awt.Font("Segoe UI", 0, 10));
        quantityList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(quantityList);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 40, 30));

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 5));

        amountList.setBackground(new java.awt.Color(204, 204, 204));
        amountList.setFont(new java.awt.Font("Segoe UI", 0, 10));
        amountList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(amountList);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 80, 30));

        pushButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        pushButton.setForeground(new java.awt.Color(0, 51, 204));
        pushButton.setText("Enter");
        pushButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pushButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushButtonActionPerformed(evt);
            }
        });
        add(pushButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 70, 30));

        warningLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        warningLabel.setForeground(new java.awt.Color(255, 0, 0));
        add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 280, 30));

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        resetButton.setForeground(new java.awt.Color(0, 0, 255));
        resetButton.setText("New ");
        resetButton.setActionCommand("");
        resetButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 20));

        Product1.setBackground(new java.awt.Color(153, 255, 204));
        Product1.setFont(new java.awt.Font("Tahoma", 0, 14));
        Product1.setForeground(new java.awt.Color(0, 51, 204));
        Product1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Product1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product1MouseClicked(evt);
            }
        });
        add(Product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 260, 30));
        Product1.setVisible(false);

        Product2.setFont(new java.awt.Font("Tahoma", 0, 14));
        Product2.setForeground(new java.awt.Color(0, 51, 204));
        Product2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Product2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product2MouseClicked(evt);
            }
        });
        add(Product2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 260, 30));
        Product2.setVisible(false);

        Product3.setBackground(new java.awt.Color(153, 255, 204));
        Product3.setFont(new java.awt.Font("Tahoma", 0, 14));
        Product3.setForeground(new java.awt.Color(0, 51, 204));
        Product3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Product3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product3MouseClicked(evt);
            }
        });
        add(Product3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 260, 30));
        Product3.setVisible(false);

        Product4.setFont(new java.awt.Font("Tahoma", 0, 14));
        Product4.setForeground(new java.awt.Color(0, 51, 204));
        Product4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Product4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product4MouseClicked(evt);
            }
        });
        add(Product4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 260, 30));
        Product4.setVisible(false);

        Product5.setBackground(new java.awt.Color(153, 255, 204));
        Product5.setFont(new java.awt.Font("Tahoma", 0, 14));
        Product5.setForeground(new java.awt.Color(0, 51, 204));
        Product5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Product5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product5MouseClicked(evt);
            }
        });
        add(Product5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 260, 30));
        Product5.setVisible(false);

        Product6.setFont(new java.awt.Font("Tahoma", 0, 14));
        Product6.setForeground(new java.awt.Color(0, 51, 204));
        Product6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Product6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product6MouseClicked(evt);
            }
        });
        add(Product6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 260, 30));
        Product6.setVisible(false);

        printButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        printButton.setForeground(new java.awt.Color(0, 51, 204));
        printButton.setText("Save");
        printButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 90, 30));

        automaticRadioButton.setBackground(new java.awt.Color(204, 204, 204));
        automaticRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        automaticRadioButton.setForeground(new java.awt.Color(0, 0, 255));
        automaticRadioButton.setText("Auto");
        automaticRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automaticRadioButtonActionPerformed(evt);
            }
        });
        add(automaticRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 20));

        Product7.setFont(new java.awt.Font("Tahoma", 0, 14));
        Product7.setForeground(new java.awt.Color(0, 51, 204));
        Product7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Product7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product7MouseClicked(evt);
            }
        });
        add(Product7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 260, 30));
        Product7.setVisible(false);

        Product8.setFont(new java.awt.Font("Tahoma", 0, 14));
        Product8.setForeground(new java.awt.Color(0, 51, 204));
        Product8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Product8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product8MouseClicked(evt);
            }
        });
        add(Product8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 740, 260, 30));
        Product8.setVisible(false);

        Product9.setFont(new java.awt.Font("Tahoma", 0, 14));
        Product9.setForeground(new java.awt.Color(0, 51, 204));
        Product9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Product9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product9MouseClicked(evt);
            }
        });
        add(Product9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 770, 260, 30));
        Product9.setVisible(false);

        successLabel.setBackground(new java.awt.Color(153, 153, 153));
        successLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        successLabel.setForeground(new java.awt.Color(255, 0, 51));
        successLabel.setText("* Successful");
        add(successLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 100, 20));
        successLabel.setVisible(false);

        jScrollPane4.setFont(new java.awt.Font("Tahoma", 0, 5));

        rateList.setBackground(new java.awt.Color(204, 204, 204));
        rateList.setFont(new java.awt.Font("Segoe UI", 0, 10));
        rateList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(rateList);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 40, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Maharajgung , Kathmandu");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Pan No .   ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 26, 110, 20));

        customerNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jPanel1.add(customerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 26, 130, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel18.setForeground(new java.awt.Color(0, 51, 204));
        jLabel18.setText("Date");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 30, 10));

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jPanel1.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, 30));

        jLabel20.setBackground(new java.awt.Color(0, 153, 102));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel20.setForeground(new java.awt.Color(0, 51, 204));
        jLabel20.setText("  Qty");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 30, 20));

        jLabel17.setBackground(new java.awt.Color(0, 153, 102));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel17.setForeground(new java.awt.Color(0, 51, 204));
        jLabel17.setText(" Rate");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 30, 20));

        jLabel19.setBackground(new java.awt.Color(0, 153, 102));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel19.setForeground(new java.awt.Color(0, 51, 204));
        jLabel19.setText("Amount ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel22.setForeground(new java.awt.Color(0, 51, 204));
        jLabel22.setText("Name :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 10));

        billNo.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jPanel1.add(billNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 40, 20));

        jLabel21.setBackground(new java.awt.Color(0, 153, 102));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel21.setForeground(new java.awt.Color(0, 51, 204));
        jLabel21.setText("Item");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 40, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText("Receit No. ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel16.setForeground(new java.awt.Color(0, 51, 204));
        jLabel16.setText("Uma Ayurveda Bhawan/Lokman Pharma");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, 90));

        totalAmountLabel.setBackground(new java.awt.Color(204, 204, 255));
        totalAmountLabel.setFont(new java.awt.Font("Calibri", 0, 24));
        totalAmountLabel.setText("00.00 NRS");
        add(totalAmountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 190, 40));

        jLabel1.setText("Charge ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 20));

        jLabel2.setText("Change ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 20));

        filler2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 10, 780));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel15.setForeground(new java.awt.Color(0, 51, 204));
        jLabel15.setText("Amount");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 60, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel23.setForeground(new java.awt.Color(0, 51, 204));
        jLabel23.setText("Tender ");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 60, 36));

        disButton.setBackground(new java.awt.Color(204, 204, 204));
        disButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        disButton.setForeground(new java.awt.Color(0, 0, 255));
        disButton.setText("Discount");
        disButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                disButtonStateChanged(evt);
            }
        });
        disButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disButtonActionPerformed(evt);
            }
        });
        add(disButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 20));

        disField.setFont(new java.awt.Font("Calibri", 0, 18));
        disField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                disFieldMouseExited(evt);
            }
        });
        disField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disFieldActionPerformed(evt);
            }
        });
        disField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                disFieldFocusLost(evt);
            }
        });
        add(disField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 100, 30));
        upqLabel.setVisible(false);
        disField.setVisible(false);
        disField.setText("0");

        percentField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                percentFieldFocusLost(evt);
            }
        });
        percentField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                percentFieldKeyReleased(evt);
            }
        });
        add(percentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 50, 30));
        percentField.setVisible(false);
        percentField.setText("0");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, 200, -1));
        add(itemSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 50, 20));

        DeleteRadio.setText("Delete");
        DeleteRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DeleteRadioStateChanged(evt);
            }
        });
        add(DeleteRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 70, -1));

        EditRadio.setText("Edit");
        EditRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EditRadioStateChanged(evt);
            }
        });
        EditRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditRadioActionPerformed(evt);
            }
        });
        add(EditRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 60, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 70, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameFieldActionPerformed

  //customerNameLabel.repaint();
  // TODO add your handling code here:
    }//GEN-LAST:event_customerNameFieldActionPerformed

    private void customerLocationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerLocationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerLocationFieldActionPerformed

    private void particularFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_particularFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_particularFieldActionPerformed

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed

    }//GEN-LAST:event_amountFieldActionPerformed

    private void KeyTypedHandeler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyTypedHandeler
  
    }//GEN-LAST:event_KeyTypedHandeler

    private void MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseExited
   customerName=customerNameField.getText();
  customerNameLabel.setText(customerName);
  customerNameLabel.setVisible(false);
   customerNameLabel.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_MouseExited

    private void TextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TextChanged
         // TODO add your handling code here:
    }//GEN-LAST:event_TextChanged

    private void TextValuechanged(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_TextValuechanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValuechanged

    private void particularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_particularKeyTyped

  // TODO add your handling code here:
    }//GEN-LAST:event_particularKeyTyped

    private void ParticularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParticularMouseExited

    }//GEN-LAST:event_ParticularMouseExited

    private void QuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityKeyTyped

    }//GEN-LAST:event_QuantityKeyTyped

    private void QuantityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuantityMouseExited
     
        if(!quantityField.getText().matches("[0-9][0-9]*\\.?[0-9]*"))
        {
            warningLabel.setText("Invalid Quantity !");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        } 
        else {
            warningLabel.setText(" ");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);// TODO add your handling code here:
              }
    }//GEN-LAST:event_QuantityMouseExited

    private void RateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RateKeyTyped
  
    }//GEN-LAST:event_RateKeyTyped

    private void RateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RateMouseExited
  if(!rateField.getText().matches("[0-9][0-9]*\\.?[0-9]*")) {
            warningLabel.setText("Invalid Rate !");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        } 
  else {  
     float qty=0;
     float rate=0;
     if(!"".equals(quantityField.getText().trim()))
      qty=new Float(quantityField.getText());
      if(rateField.getText()!=null)
      rate=new Float(rateField.getText());
            Float amount=rate*qty;
            amountField.setText(amount.toString());
            warningLabel.setText(" ");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        warningLabel.setText(" ");
        warningLabel.setVisible(false);
        warningLabel.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_RateMouseExited

    private void AmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountKeyTyped
    // TODO add your handling code here:
    }//GEN-LAST:event_AmountKeyTyped

    private void AmountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AmountMouseExited
if(!amountField.getText().matches("[0-9][0-9]*\\.?[0-9]*")) {
            warningLabel.setText("Invalid Amount !!! ");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        } 
else {    warningLabel.setText(" ");
        warningLabel.setVisible(false);
        warningLabel.setVisible(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_AmountMouseExited

    private void CashReceivedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CashReceivedKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CashReceivedKeyTyped

    private void CashReceivedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CashReceivedMouseExited
  Float cashReceived=new Float(0);
        if(cashReceivedField.getText().matches("[0-9]+\\.?[0-9]*")) {
        cashReceived=new Float(cashReceivedField.getText()); 
        warningLabel.setText(" ");
        warningLabel.setVisible(false);
        warningLabel.setVisible(true);
            NumberFormat formatter = NumberFormat.getInstance(new Locale("en_US"));
        BigDecimal bd = new BigDecimal(Math.round((cashReceived.floatValue()-totalAmount.floatValue()+new Float(disField.getText()))*100.00)/100.00);  
        changeLabel.setText(formatter.format(bd.floatValue())+" NRS");
        }
        else 
            warningLabel.setText("Invalid Tender amount !");// TODO add your handling code here:
    }//GEN-LAST:event_CashReceivedMouseExited

    private void rateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateFieldActionPerformed
    
    private void pushButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushButtonActionPerformed
if(amountField.getText().matches("[0-9][0-9]*\\.?[0-9]*"))
{
String productName=" ";
String amtVal="0";
String rateVal="0";
String qtyVal="0";
if(!"".equals(particularField.getText().trim()))
productName=particularField.getText();
if(!"".equals(amountField.getText().trim()))
amtVal=amountField.getText();
if(!"".equals(rateField.getText().trim()))
rateVal=rateField.getText();
if(!"".equals(quantityField.getText().trim()))
qtyVal=quantityField.getText();
if(!"".equals(particularField.getText().trim()+amountField.getText().trim()))
{
        ArrayList<String> smallBill=new ArrayList<String>(); 
        smallBill.add(0,row_wid);
        smallBill.add(1,productName); // add the product name to list 
        smallBill.add(2,qtyVal);   // product quantity to the list
        smallBill.add(3,rateVal);//  product value to the list 
        smallBill.add(4,amtVal); 
         totalAmount+=new Float(amtVal); 
        NumberFormat formatter = NumberFormat.getInstance(new Locale("en_US"));
         BigDecimal bd = new BigDecimal(Math.round(totalAmount*100.0)/100.0);   
        totalAmountLabel.setText(formatter.format(bd.floatValue())+" NRS"); 
        billData.add(smallBill);                        // add to the big bill 
        ArrayList<String> illusion1=new ArrayList<String>();
        ArrayList<String> illusion2=new ArrayList<String>();
        ArrayList<String> illusion3=new ArrayList<String>();
        ArrayList<String> illusion4=new ArrayList<String>();
        int sn=0;
            
        for( ArrayList<String> smallBil : billData) {
            if(smallBil.get(1).length()>25)
            illusion1.add(++sn+"."+smallBil.get(1).substring(1,25)+"...");
            else
               illusion1.add(++sn+". "+smallBil.get(1)); 
            illusion2.add(smallBil.get(2));
            totalAmountLabel.setText(formatter.format(bd.floatValue())+" NRS");
            illusion3.add(smallBil.get(4)); 
            illusion4.add(smallBil.get(3));
        }    
            illusion1.add(" "); 
            illusion2.add(" ");
            illusion4.add(" ");
            illusion3.add(" ");
            illusion1.add("TOTAL AMOUNT"); 
            illusion2.add(" ");
            illusion4.add(" ");
            illusion3.add(formatter.format(bd.floatValue())+" NRS");
        ParticularList.setListData(illusion1.toArray());
        ParticularList.setVisible(false); // printing the list on the bill 
        ParticularList.setVisible(true);
        quantityList.setListData(illusion2.toArray());
        quantityList.setVisible(false);
        quantityList.setVisible(true);
       rateList.setListData(illusion4.toArray());
        rateList.setVisible(false);
        rateList.setVisible(true);
        amountList.setListData(illusion3.toArray());
        amountList.setVisible(false);
        amountList.setVisible(true);
}
        
        particularField.setText("");// reset the field after push
        rateField.setText("");
        quantityField.setText("");
        amountField.setText("");
        row_wid="";

this.remove(jScrollPane1);
this.remove(jScrollPane2);
this.remove(jScrollPane3);
this.remove(jScrollPane4);

billHeight+=22;
totalListHeight+=10;
graphicsHeight+=10;

add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, billHeight));
  add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 40, billHeight));
 add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 80, billHeight));
add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 40, billHeight));
 jScrollPane1.setVisible(false);
  jScrollPane2.setVisible(false);
   jScrollPane3.setVisible(false);
    jScrollPane4.setVisible(false);
jScrollPane1.setVisible(true);
  jScrollPane2.setVisible(true);
   jScrollPane3.setVisible(true);
    jScrollPane4.setVisible(true);
}



    }//GEN-LAST:event_pushButtonActionPerformed

    private void cashReceivedFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashReceivedFieldFocusLost
        Float cashReceived=new Float(0);
        if(cashReceivedField.getText().matches("[0-9]+\\.?[0-9]*")) {
        cashReceived=new Float(cashReceivedField.getText()); 
        warningLabel.setText(" ");
        warningLabel.setVisible(false);
        warningLabel.setVisible(true);
            NumberFormat formatter = NumberFormat.getInstance(new Locale("en_US"));
        BigDecimal bd = new BigDecimal(Math.round((cashReceived.floatValue()-totalAmount.floatValue()+new Float(disField.getText()))*100.00)/100.00);  
        changeLabel.setText(formatter.format(bd.floatValue())+" NRS");
        }
        else 
            warningLabel.setText("Invalid Tender amount !");
    }//GEN-LAST:event_cashReceivedFieldFocusLost

    private void rateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateFieldFocusLost
   if(!rateField.getText().matches("[0-9][0-9]*\\.?[0-9]*")) {
            warningLabel.setText("Invalid Rate !");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        } 
   else {  
     float qty=0;
     float rate=0;
     if(!"".equals(quantityField.getText().trim()))
      qty=new Float(quantityField.getText());
      if(!"".equals(rateField.getText().trim()))
      rate=new Float(rateField.getText());
            Float amount=rate*qty;
            amountField.setText(amount.toString());
            warningLabel.setText(" ");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        warningLabel.setText(" ");
        warningLabel.setVisible(false);
        warningLabel.setVisible(true);}       // TODO add your handling code here:
    }//GEN-LAST:event_rateFieldFocusLost

    private void quantityFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityFieldFocusLost
  if(!quantityField.getText().matches("[0-9][0-9]*\\.?[0-9]*")) {
            warningLabel.setText("Invalid Quantity !");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldFocusLost

    private void customerNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameFieldFocusLost
 customerName=customerNameField.getText();
  customerNameLabel.setText(customerName);
  customerNameLabel.setVisible(false);
   customerNameLabel.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameFieldFocusLost

    private void KeyTypedForDate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyTypedForDate
            // TODO add your handling code here:
}//GEN-LAST:event_KeyTypedForDate

    private void dateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFieldFocusLost
        date=dateField.getText();   
        dateLabel.setText(date);
        dateLabel.setVisible(false);
        dateLabel.setVisible(true);         // TODO add your handling code here:
}//GEN-LAST:event_dateFieldFocusLost

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dateFieldActionPerformed

    private void DateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateMouseExited
        date=dateField.getText();
        dateLabel.setText(date);
        dateLabel.setVisible(false);
        dateLabel.setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_DateMouseExited

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed

        try {
billHeight=30;
totalListHeight=325;
graphicsHeight=145;
            particularField.setText("");
            customerNameLabel.setText("");
            customerNameField.setText("");
            changeLabel.setText("");
            cashReceivedField.setText("");
            warningLabel.setText("");
            rateField.setText("");
            customerLocationField.setText("");
            changeLabel.setText(" 0.0 NRS");
            totalAmountLabel.setText(" 0.0 NRS");
            percentField.setText("0");
            disField.setText("0");
                   
                        SalesModel pm=new SalesModel();
                        billNo.setText(pm.lastSalesId()+"");
                        billNo.setVisible(false);
                        billNo.setVisible(true);
            ArrayList<String> a=new ArrayList<String>();
            a.add(" ");
            ParticularList.setListData(a.toArray());
            amountList.setListData(a.toArray());
            quantityList.setListData(a.toArray());
            rateList.setListData(a.toArray());
            totalAmount=new Float(0);
            billData =new ArrayList<ArrayList<String>>();
            successLabel.setVisible(false);

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(BillingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void customerNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerNameFieldKeyReleased
  customerNameLabel.setText(customerNameField.getText());
  customerNameLabel.setVisible(false);
  customerNameLabel.setVisible(true);    
  SimpleDateFormat d = new SimpleDateFormat ("yyyy/MM/dd");    
  dateField.setText(d.format(new Date()));        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameFieldKeyReleased

    private void rateFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rateFieldKeyReleased
 if(!rateField.getText().matches("[0-9]*\\.?[0-9]*"))
{      warningLabel.setText("Invalid Rate !");
       warningLabel.setVisible(false);
       warningLabel.setVisible(true);
}
   else {    warningLabel.setText(" ");
       warningLabel.setVisible(false);
       warningLabel.setVisible(true);}        // TODO add your handling code here:
    }//GEN-LAST:event_rateFieldKeyReleased

    private void quantityFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityFieldKeyReleased
if(!quantityField.getText().matches("[0-9]*\\.?[0-9]*"))
{      warningLabel.setText("Invalid Quantity !");
       warningLabel.setVisible(false);
       warningLabel.setVisible(true);
}   
else {   
       warningLabel.setText(" ");
       warningLabel.setVisible(false);
       warningLabel.setVisible(true);
      }        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldKeyReleased

    private void Product1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product1MouseClicked
        try {
            String[] name=Product1.getText().split("#");
            particularField.setText(name[0]);
            SalesModel pm=new SalesModel();
            ArrayList<String> list=pm.getProductRow(name[0]);
            rateField.setText(list.get(2));
            row_wid=list.get(0);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_Product1MouseClicked

    private void Product2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product2MouseClicked
        try {
            String[] name=Product2.getText().split("#");
            particularField.setText(name[0]);
            SalesModel pm=new SalesModel();
            ArrayList<String> list=pm.getProductRow(name[0]);
            rateField.setText(list.get(2));
            row_wid=list.get(0);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
}//GEN-LAST:event_Product2MouseClicked

    private void Product3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product3MouseClicked
        try {
            String[] name=Product3.getText().split("#");
            particularField.setText(name[0]);
            SalesModel pm=new SalesModel();
            ArrayList<String> list=pm.getProductRow(name[0]);
            rateField.setText(list.get(2));
            row_wid=list.get(0);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
}//GEN-LAST:event_Product3MouseClicked

    private void Product4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product4MouseClicked
        try {
            String[] name=Product4.getText().split("#");
            particularField.setText(name[0]);
            SalesModel pm=new SalesModel();
            ArrayList<String> list=pm.getProductRow(name[0]);
            rateField.setText(list.get(2));
            row_wid=list.get(0);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
}//GEN-LAST:event_Product4MouseClicked

    private void Product5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product5MouseClicked
        try {
            String[] name=Product5.getText().split("#");
            particularField.setText(name[0]);
            SalesModel pm=new SalesModel();
            ArrayList<String> list=pm.getProductRow(name[0]);
            rateField.setText(list.get(2));
            row_wid=list.get(0);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
}//GEN-LAST:event_Product5MouseClicked

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            SalesModel pm=new SalesModel();
                      InventoryModel im=new InventoryModel();
                      String tranx_id=pm.lastSalesId();
                      billNo.setText(tranx_id);
                      billNo.setVisible(false);
                      billNo.setVisible(true);
  PageFormat format = new PageFormat();
   Paper paper = new Paper();
   double paperWidth = 3.2;
   double paperHeight = 11.69;
   double leftMargin = 0.2;
   double rightMargin = 0.2;
   double topMargin = 0.05;
   double bottomMargin = 0.01;
   paper.setSize(paperWidth * 72.0, paperHeight * 72.0);
   paper.setImageableArea(leftMargin * 72.0, topMargin * 72.0,
        (paperWidth - leftMargin - rightMargin) * 72.0,
        (paperHeight - topMargin - bottomMargin) * 72.0);
   format.setPaper(paper);
   PrintRequestAttributeSet aset = new HashPrintRequestAttributeSet();
   aset.add(OrientationRequested.PORTRAIT);
   PrinterJob printerJob = PrinterJob.getPrinterJob();
   Printable printable = new ReceiptPrintTest();
   format = printerJob.validatePage(format);
   printerJob.setPrintable(printable, format);
                 printerJob.setPrintable(this);
          
                      try  
                      {  
                          printerJob.print(aset);
                      } // end try  
                      catch (Exception ex)  
                      {  
                          ex.printStackTrace();  
                      } // end Exception catch  
                      //   Be sure all happening in your life is my plan for you .  
                  try {
                     
                      for(ArrayList<String> list: billData) {    
                          if("".equals(list.get(0)))// if it is not recorded in PROD_DIM table
                          {
                              pm.insertProducDim(list.get(1),list.get(3));  // insert in PROD_DIM table
                              String prod_wid=pm.lastProId();  // get the prod id
                              pm.insertSalesFact(prod_wid,list.get(2),list.get(4),tranx_id);
                              im.addInventory(prod_wid);
                              im.subtractInventory(prod_wid,list.get(2));// insert in purchase fact
                          } 
                          else {
                              pm.insertSalesFact(list.get(0),list.get(2),list.get(4),tranx_id); 
                              im.subtractInventory(list.get(0),list.get(2));// insert in purchase fact with already acquised PROD_WID
                          }
                      }
                       if(disField.getText().matches("[0-9][0-9]*\\.?[0-9]*"))
                    pm.insertSalesTranxDtl(tranx_id,customerNameField.getText(),customerLocationField.getText(),totalAmount+"",disField.getText());
                     
                       else
                           pm.insertSalesTranxDtl(tranx_id,customerNameField.getText(),customerLocationField.getText(),totalAmount+"",0+"");
                    
                           
                  } catch (SQLException ex) {
                      Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
                  }
          particularField.setText("");
          customerNameLabel.setText("");
          customerNameField.setText("");
          cashReceivedField.setText("");
          warningLabel.setText("");
          rateField.setText("");
          customerLocationField.setText("");
          ArrayList<String> a=new ArrayList<String>();
          a.add(" ");
          ParticularList.setListData(a.toArray());
          amountList.setListData(a.toArray());
          quantityList.setListData(a.toArray());
          rateList.setListData(a.toArray());
          totalAmount=new Float(0);
          billData =new ArrayList<ArrayList<String>>();
          successLabel.setVisible(true);
                      
                      tranx_id=pm.lastSalesId();
                      billNo.setText(tranx_id);
                      billNo.setVisible(false);
                      billNo.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(BillingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_printButtonActionPerformed

    private void particularFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_particularFieldKeyReleased
try {
             SalesModel pm=new SalesModel();
             Product1.setVisible(false);
             Product2.setVisible(false);
             Product3.setVisible(false);
              Product4.setVisible(false);
              Product5.setVisible(false);
              Product6.setVisible(false);
              Product7.setVisible(false);
              Product8.setVisible(false);
              Product9.setVisible(false);
              
            if(particularField.getText().trim().length()>0)
            {
            ArrayList<String> productList=pm.getProductName(particularField.getText());
            
             if(productList.size()>=9)
              {
              
              Product1.setText(productList.get(0));
              Product1.setVisible(true);              
              Product2.setText(productList.get(1));
              Product2.setVisible(true);              
              Product3.setText(productList.get(2));
              Product3.setVisible(true);
              Product4.setText(productList.get(3));
              Product4.setVisible(true);
              Product5.setText(productList.get(4));
              Product5.setVisible(true);
              Product6.setText(productList.get(5));
              Product6.setVisible(true);
              Product7.setText(productList.get(6));
              Product7.setVisible(true);
              Product8.setText(productList.get(7));
              Product8.setVisible(true);
              Product9.setText(productList.get(8));
              Product9.setVisible(true);
              
              }
              else if(productList.size()>=8)
              {
              
              Product1.setText(productList.get(0));
              Product1.setVisible(true);              
              Product2.setText(productList.get(1));
              Product2.setVisible(true);              
              Product3.setText(productList.get(2));
              Product3.setVisible(true);
              Product4.setText(productList.get(3));
              Product4.setVisible(true);
              Product5.setText(productList.get(4));
              Product5.setVisible(true);
              Product6.setText(productList.get(5));
              Product6.setVisible(true);
              Product7.setText(productList.get(6));
              Product7.setVisible(true);
              Product8.setText(productList.get(7));
              Product8.setVisible(true);
              }
                      
                      else if(productList.size()>=7)
              {
              
              Product1.setText(productList.get(0));
              Product1.setVisible(true);              
              Product2.setText(productList.get(1));
              Product2.setVisible(true);              
              Product3.setText(productList.get(2));
              Product3.setVisible(true);
              Product4.setText(productList.get(3));
              Product4.setVisible(true);
              Product5.setText(productList.get(4));
              Product5.setVisible(true);
              Product6.setText(productList.get(5));
              Product6.setVisible(true);
              Product7.setText(productList.get(5));
              Product7.setVisible(true);
              Product7.setText(productList.get(6));
              Product7.setVisible(true);
              }
             else if(productList.size()>=6)
              {              
              Product1.setText(productList.get(0));
              Product1.setVisible(true);              
              Product2.setText(productList.get(1));
              Product2.setVisible(true);              
              Product3.setText(productList.get(2));
              Product3.setVisible(true);
              Product4.setText(productList.get(3));
              Product4.setVisible(true);
              Product5.setText(productList.get(4));
              Product5.setVisible(true);
              Product6.setText(productList.get(5));
              Product6.setVisible(true); 
              }
              
             else if(productList.size()>=5)
              {
              
              Product1.setText(productList.get(0));
              Product1.setVisible(true);              
              Product2.setText(productList.get(1));
              Product2.setVisible(true);              
              Product3.setText(productList.get(2));
              Product3.setVisible(true);
              Product4.setText(productList.get(3));
              Product4.setVisible(true);
              Product5.setText(productList.get(4));
              Product5.setVisible(true);
              
              }
              
               else if(productList.size()>=4)
              {
              
              Product1.setText(productList.get(0));
              Product1.setVisible(true);              
              Product2.setText(productList.get(1));
              Product2.setVisible(true);              
              Product3.setText(productList.get(2));
              Product3.setVisible(true);
              Product4.setText(productList.get(3));
              Product4.setVisible(true);
              }
               else if(productList.size()>=3)
              {
              
              Product1.setText(productList.get(0));
              Product1.setVisible(true);              
              Product2.setText(productList.get(1));
              Product2.setVisible(true);              
              Product3.setText(productList.get(2));
              Product3.setVisible(true);
              }
               else if(productList.size()>=2)
              {
              
              Product1.setText(productList.get(0));
              Product1.setVisible(true);              
              Product2.setText(productList.get(1));
              Product2.setVisible(true);           
              }
               else if(productList.size()>=1)
              {
              
              Product1.setText(productList.get(0));
               Product1.setVisible(true); 
              if(automaticRadioButton.isSelected())
              {
              String[] arrStr=productList.get(0).split("#");
              particularField.setText(arrStr[0]);
              String[] name=Product1.getText().split("#"); 
              particularField.setText(name[0]);
   //uncomment if you want to automate : recommended for old databases
              ArrayList<String> list=pm.getProductRow(name[0]); 
              rateField.setText(list.get(2));
              row_wid=list.get(0);
                      
              }}
               else {}
              
              }
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
        
        
        }     
    }//GEN-LAST:event_particularFieldKeyReleased

    private void particularFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_particularFieldFocusLost
             Product1.setVisible(false);
             Product2.setVisible(false);
             Product3.setVisible(false);
              Product4.setVisible(false);
              Product5.setVisible(false);
              Product6.setVisible(false); 
              Product7.setVisible(false);  
              Product8.setVisible(false);  
              Product9.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_particularFieldFocusLost

    private void automaticRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automaticRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_automaticRadioButtonActionPerformed

    private void Product7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product7MouseClicked
 try {
            String[] name=Product7.getText().split("#");
            particularField.setText(name[0]);
            SalesModel pm=new SalesModel();
            ArrayList<String> list=pm.getProductRow(name[0]);
            rateField.setText(list.get(2));
            row_wid=list.get(0);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Product7MouseClicked

    private void Product8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product8MouseClicked
    try {
            String[] name=Product8.getText().split("#");
            particularField.setText(name[0]);
            SalesModel pm=new SalesModel();
            ArrayList<String> list=pm.getProductRow(name[0]);
            rateField.setText(list.get(2));
            row_wid=list.get(0);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_Product8MouseClicked

    private void Product9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product9MouseClicked
       try {
            String[] name=Product9.getText().split("#");
            particularField.setText(name[0]);
            SalesModel pm=new SalesModel();
            ArrayList<String> list=pm.getProductRow(name[0]);
            rateField.setText(list.get(2));
            row_wid=list.get(0);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
        } // TODO add your handling code here:
    }//GEN-LAST:event_Product9MouseClicked

    private void Product6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product6MouseClicked
        try {
            String[] name=Product6.getText().split("#");
            particularField.setText(name[0]);
            SalesModel pm=new SalesModel();
            ArrayList<String> list=pm.getProductRow(name[0]);
            rateField.setText(list.get(2));
            row_wid=list.get(0);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseForm.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
}//GEN-LAST:event_Product6MouseClicked

    private void amountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyReleased
if(!amountField.getText().matches("[0-9][0-9]*\\.?[0-9]*")) {
            warningLabel.setText("Invalid Amount !!! ");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        } else {    warningLabel.setText(" ");
        warningLabel.setVisible(false);
        warningLabel.setVisible(true);}        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldKeyReleased

    private void amountFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFieldFocusLost
    if(!amountField.getText().matches("[0-9][0-9]*\\.?[0-9]*")) {
            warningLabel.setText("Invalid Amount !!! ");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        } else {    warningLabel.setText(" ");
        warningLabel.setVisible(false);
        warningLabel.setVisible(true);}      // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldFocusLost

    private void cashReceivedFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashReceivedFieldKeyReleased
  Float cashReceived=new Float(0);
        if(cashReceivedField.getText().matches("[0-9]+\\.?[0-9]*")) {
        cashReceived=new Float(cashReceivedField.getText()); 
        warningLabel.setText(" ");
        warningLabel.setVisible(false);
        warningLabel.setVisible(true);
            NumberFormat formatter = NumberFormat.getInstance(new Locale("en_US"));
        BigDecimal bd = new BigDecimal(Math.round((cashReceived.floatValue()-totalAmount.floatValue()+new Float(disField.getText()))*100.00)/100.00);  
        changeLabel.setText(formatter.format(bd.floatValue())+" NRS");
        }
        else 
            warningLabel.setText("Invalid Tender amount !");
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_cashReceivedFieldKeyReleased

    private void disButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_disButtonStateChanged
        if(disButton.isSelected()) {
            upqLabel.setVisible(true);
            disField.setVisible(true);
             percentField.setVisible(true);
            isPack=true;
            rateBox.select(3);
        } else {
            percentField.setVisible(false);
            upqLabel.setVisible(false);
            disField.setVisible(false);
            isPack=false;
        }
        
        // TODO add your handling code here:
}//GEN-LAST:event_disButtonStateChanged

    private void disButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_disButtonActionPerformed

    private void disFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disFieldMouseExited
        if(disField.getText().matches("[0-9][0-9]*\\.?[0-9]*"))
        {
        NumberFormat formatter = NumberFormat.getInstance(new Locale("en_US"));
            float value=totalAmount-new Float(disField.getText());
            discAmt=new Float(disField.getText());
       BigDecimal bd = new BigDecimal(Math.round(value*100.0)/100.0);        
            totalAmountLabel.setText(formatter.format(bd.floatValue())+" NRS");
        
        }
        else warningLabel.setText("Invalid Discount");
        totalAmountLabel.setVisible(false);
        totalAmountLabel.setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_disFieldMouseExited

    private void disFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_disFieldActionPerformed

    private void disFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_disFieldFocusLost
        if(disField.getText().matches("[0-9][0-9]*\\.?[0-9]*"))
        {
            NumberFormat formatter = NumberFormat.getInstance(new Locale("en_US"));
            float value=totalAmount-new Float(disField.getText());
       BigDecimal bd = new BigDecimal(Math.round(value*100.0)/100.0);        
            totalAmountLabel.setText(formatter.format(bd.floatValue())+" NRS");
           discAmt=new Float(disField.getText());
        }
        else warningLabel.setText("Invalid Discount");
        totalAmountLabel.setVisible(false);
        totalAmountLabel.setVisible(true); // TODO add your handling code here:
}//GEN-LAST:event_disFieldFocusLost

    private void percentFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_percentFieldFocusLost
if(percentField.getText().matches("[0-9][0-9]*\\.?[0-9]*"))
        {
            NumberFormat formatter = NumberFormat.getInstance(new Locale("en_US"));
            float value=totalAmount*(1-(new Float(percentField.getText()))/100);
       BigDecimal bd = new BigDecimal(Math.round(value*100.0)/100.0);        
            totalAmountLabel.setText(formatter.format(bd.floatValue())+" NRS");
            disField.setText(totalAmount*(new Float(percentField.getText())/100)+"");
           discAmt=new Float(disField.getText());
        }
        else warningLabel.setText("Invalid Discount");
        totalAmountLabel.setVisible(false);
        totalAmountLabel.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_percentFieldFocusLost

    private void percentFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percentFieldKeyReleased
if(percentField.getText().matches("[0-9][0-9]*\\.?[0-9]*"))
        {
            NumberFormat formatter = NumberFormat.getInstance(new Locale("en_US"));
            float value=totalAmount*(1-(new Float(percentField.getText()))/100);
       BigDecimal bd = new BigDecimal(Math.round(value*100.0)/100.0);        
            totalAmountLabel.setText(formatter.format(bd.floatValue())+" NRS");
            disField.setText(totalAmount*(new Float(percentField.getText())/100)+"");
           discAmt=new Float(disField.getText());
        }
        else warningLabel.setText("Invalid Discount");
        totalAmountLabel.setVisible(false);
        totalAmountLabel.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_percentFieldKeyReleased

    private void EditRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditRadioActionPerformed
        // TODO add your handling code here
if(EditRadio.isSelected()&& new Integer(itemSelector.getValue().toString())>0)
{
 ArrayList<String> smallBill=billData.get(new Integer(itemSelector.getValue().toString())-1);
  
        particularField.setText(smallBill.get(1)); // add the product name to list 
        quantityField.setText(smallBill.get(2));   // product quantity to the list
        rateField.setText(smallBill.get(3));//  product value to the list 
        amountField.setText(smallBill.get(4)); 
}
    }//GEN-LAST:event_EditRadioActionPerformed

    private void EditRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EditRadioStateChanged
if(EditRadio.isSelected()&& new Integer(itemSelector.getValue().toString())>0)
{
    

}// TODO add your handling code here:
    }//GEN-LAST:event_EditRadioStateChanged

    private void DeleteRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DeleteRadioStateChanged
       // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRadioStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(DeleteRadio.isSelected()&& new Integer(itemSelector.getValue().toString())>0)
{
System.out.println(billData);
totalAmount-=new Float(billData.get(new Integer(itemSelector.getValue().toString())-1).get(4));
billData.remove(new Integer(itemSelector.getValue().toString())-1);
System.out.println(billData);
}

if(EditRadio.isSelected()&& new Integer(itemSelector.getValue().toString())>0)
{ 
String productName=" ";
String amtVal="0";
String rateVal="0";
String qtyVal="0";
if(!"".equals(particularField.getText().trim()))
productName=particularField.getText();
if(!"".equals(amountField.getText().trim()))
amtVal=amountField.getText();
if(!"".equals(rateField.getText().trim()))
rateVal=rateField.getText();
if(!"".equals(quantityField.getText().trim()))
qtyVal=quantityField.getText();
if(!"".equals(particularField.getText().trim()+amountField.getText().trim()))
{       totalAmount-=new Float(billData.get(new Integer(itemSelector.getValue().toString())-1).get(4));
       ArrayList<String> smallBill=new ArrayList<String>(); 
        smallBill.add(0,row_wid);
        smallBill.add(1,productName); //add the product name to list 
        smallBill.add(2,qtyVal);      //product quantity to the list
        smallBill.add(3,rateVal);     //product value to the list 
        smallBill.add(4,amtVal); 
         totalAmount+=new Float(amtVal);
System.out.println(billData);
billData.set(new Integer(itemSelector.getValue().toString())-1,smallBill);
}
}


    
         NumberFormat formatter = NumberFormat.getInstance(new Locale("en_US"));
         BigDecimal bd = new BigDecimal(Math.round(totalAmount*100.0)/100.0);  
        totalAmountLabel.setText(formatter.format(bd.floatValue())+" NRS"); 
        totalAmountLabel.setVisible(false);
        totalAmountLabel.setVisible(true);
        ArrayList<String> illusion1=new ArrayList<String>();
        ArrayList<String> illusion2=new ArrayList<String>();
        ArrayList<String> illusion3=new ArrayList<String>();
        ArrayList<String> illusion4=new ArrayList<String>();
        int sn=0;
            
        for( ArrayList<String> smallBil : billData) {
            if(smallBil.get(1).length()>25)
               illusion1.add(++sn+"."+smallBil.get(1).substring(1,25)+"...");
            else
               illusion1.add(++sn+". "+smallBil.get(1)); 
               illusion2.add(smallBil.get(2));
               totalAmountLabel.setText(formatter.format(bd.floatValue())+" NRS");
               illusion3.add(smallBil.get(4)); 
               illusion4.add(smallBil.get(3));
        }    
            illusion1.add(" "); 
            illusion2.add(" ");
            illusion4.add(" ");
            illusion3.add(" ");
            illusion1.add("TOTAL AMOUNT"); 
            illusion2.add(" ");
            illusion4.add(" ");
            illusion3.add(formatter.format(bd.floatValue())+" NRS");
        ParticularList.setListData(illusion1.toArray());
        ParticularList.setVisible(false); // printing the list on the bill 
        ParticularList.setVisible(true);
        quantityList.setListData(illusion2.toArray());
        quantityList.setVisible(false);
        quantityList.setVisible(true);
       rateList.setListData(illusion4.toArray());
        rateList.setVisible(false);
        rateList.setVisible(true);
        amountList.setListData(illusion3.toArray());
        amountList.setVisible(false);
        amountList.setVisible(true);
        
        particularField.setText("");// reset the field after push
        rateField.setText("");
        quantityField.setText("");
        amountField.setText("");
        row_wid="";
        
add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, billHeight));
add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 40, billHeight));
add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 80, billHeight));
add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 40, billHeight));

  jScrollPane1.setVisible(false);
  jScrollPane2.setVisible(false);
  jScrollPane3.setVisible(false);
  jScrollPane4.setVisible(false);
jScrollPane1.setVisible(true);
jScrollPane2.setVisible(true);
jScrollPane3.setVisible(true);
jScrollPane4.setVisible(true);
System.out.println(billData);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DeleteRadio;
    private javax.swing.JRadioButton EditRadio;
    private javax.swing.JList ParticularList;
    private javax.swing.JLabel Product1;
    private javax.swing.JLabel Product2;
    private javax.swing.JLabel Product3;
    private javax.swing.JLabel Product4;
    private javax.swing.JLabel Product5;
    private javax.swing.JLabel Product6;
    private javax.swing.JLabel Product7;
    private javax.swing.JLabel Product8;
    private javax.swing.JLabel Product9;
    private javax.swing.JTextField amountField;
    private javax.swing.JList amountList;
    private javax.swing.JRadioButton automaticRadioButton;
    private javax.swing.JLabel billNo;
    private javax.swing.JTextField cashReceivedField;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JTextField customerLocationField;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JRadioButton disButton;
    private javax.swing.JTextField disField;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JSpinner itemSelector;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField particularField;
    private javax.swing.JTextField percentField;
    private javax.swing.JButton printButton;
    private javax.swing.JButton pushButton;
    private java.awt.Choice quantityBox;
    private javax.swing.JTextField quantityField;
    private javax.swing.JList quantityList;
    private java.awt.Choice rateBox;
    private javax.swing.JTextField rateField;
    private javax.swing.JList rateList;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel successLabel;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JLabel upqLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
private String customerName=" ";
private String date;
private String customerLocation;
private ArrayList<ArrayList<String>> billData =new ArrayList<ArrayList<String>>();
Float totalAmount=new Float(0);
String row_wid="";
private int particularId=0;
private int billHeight=30;
private int totalListHeight=350;
private int graphicsHeight=145;
boolean isPack=false;
float discAmt=0;

    
    @Override
     public int print(Graphics g, PageFormat pf, int page) throws PrinterException   
        {   
                    if (page > 0) {   
            return NO_SUCH_PAGE;  
        }  
        int dx=100;
        int dy=75;
          if (page < 0 || page >= 1) {
            return Printable.NO_SUCH_PAGE;
        }

        Graphics2D g2d = (Graphics2D) g;
        g2d.translate(pf.getImageableX(), pf.getImageableY());       
          
        //The following returns the correct dimensions (612 width, 504 height).  
        System.out.println("Width: "+pf.getImageableWidth()+" Height: "+pf.getImageableHeight());  
        //g.setFont(new Font("calibri",Font.BOLD,8));
       g.setFont(new Font("TimesRoman",Font.BOLD,8));
       g.drawString(" Uma Ayurveda / Lokman Pharma ",dx+30,dy+3); 
        g.setFont(new Font("TimesRoman",Font.PLAIN,8));
       g.drawString("Maharajgunj-KTM",dx+50,dy+12);
       g.drawString("Pan No 303420543",dx+160,dy+12);
       g.drawString("Bill No. "+billNo.getText(),dx+160,dy+25);
       g.drawString("Name:",dx+1,dy+25);
       g.drawString(customerName,dx+25,dy+25); 
       g.drawString("Date:",dx+1,dy+33);
       g.drawString(dateLabel.getText(),dx+25,dy+33);
      g.setFont(new Font("TimesRoman",Font.BOLD,8));
       g.drawString("Item",dx+14,dy+43);
       g.drawString("Qty",dx+122,dy+43);
       g.drawString("Rate",dx+145,dy+43);
       g.drawString("AMT(NRS)",dx+170,dy+43);
       
       NumberFormat formatter = NumberFormat.getInstance(new Locale("en_US"));
       BigDecimal bd = new BigDecimal(Math.round(totalAmount*100.0)/100.0);     
        
      ArrayList<String> illusion1=new ArrayList<String>();
        ArrayList<String> illusion2=new ArrayList<String>();
        ArrayList<String> illusion3=new ArrayList<String>();
        ArrayList<String> illusion4=new ArrayList<String>();
        int sn=0;
            
        for( ArrayList<String> smallBil : billData) {
            if(smallBil.get(1).length()>23)
            illusion1.add(++sn+"."+smallBil.get(1).substring(0,23)+"...");
            else
               illusion1.add(++sn+". "+smallBil.get(1)); 
            illusion2.add(smallBil.get(2));
            illusion3.add(smallBil.get(4)); 
            illusion4.add(smallBil.get(3));
        }    
        if(discAmt>0)
        {      illusion1.add(" "); 
            illusion2.add(" ");
            illusion4.add(" ");
            illusion3.add(" ");
         illusion1.add("Discount "); 
            illusion2.add(" ");
            illusion4.add(" ");
            illusion3.add("-"+discAmt);
        }
            illusion1.add(" "); 
            illusion2.add(" ");
            illusion4.add(" ");
            illusion3.add(" ");
            illusion1.add("         NET TOTAL"); 
            illusion2.add(" ");
            illusion4.add(" ");
            illusion3.add(totalAmountLabel.getText());
            int incr=dy+51;
             g.setFont(new Font("TimesRoman",Font.PLAIN,8));
             
        for (String str:illusion1)  //particular ko lagi
        {
        g.drawString(str,dx+1,incr);
        incr+=8;
        }
        
        incr=dy+51;
        for (String str:illusion2) // quantity ko lagi
        {
        g.drawString(str,dx+122,incr);
        incr+=8;
        }
        
        incr=dy+51;
        for (String str:illusion4)  
        {
        g.drawString(str,dx+145,incr);
        incr+=8;
        }
        
        incr=dy+51;
        for (String str:illusion3)
        {
        g.drawString(str,dx+170,incr);
        incr+=8;
        }
       
        return PAGE_EXISTS; 
         
   
        } 
   
}  



