/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * salesDetail.java
 *
 * Created on Dec 22, 2012, 9:18:36 AM
 */
package Reporting;

import Model.InventoryModel;
import Model.PurchaseModel;
import Model.SalesModel;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paradise lost
 */
public class purchaseDetail extends javax.swing.JPanel {

    /** Creates new form salesDetail */
    public purchaseDetail() throws SQLException {
        monthsVal=new HashMap();
        String months="Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec";
        String[] monthsList = months.split(" ");
        int mthCount=1;
         for(String mthVal:monthsList)
        { String mth="1";
            if(mthCount<10)
             mth="0"+mthCount;
        else  mth=mthCount+"";
            monthsVal.put(mthVal,mth);
        mthCount++;
                    }
        dft=new DefaultTableModel();
        dft.addColumn("Date");
        dft.addColumn("Dealer Details");
        dft.addColumn("Amount");
        PurchaseModel pm=new PurchaseModel();      
        Vector<Vector<String>> resultSet=pm.getAllDetails();
        for(Vector<String> list : resultSet)
        {
            dft.addRow(list);
        } 
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        yearChoice = new java.awt.Choice();
        monthChoice = new java.awt.Choice();
        viewButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalPurAmt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        highPurDay = new javax.swing.JLabel();

        setFont(new java.awt.Font("Tahoma", 0, 14));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(dft);
        jScrollPane2.setViewportView(jTable2);

        jScrollPane3.setViewportView(jScrollPane2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 500, 660));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Purchase Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        yearChoice.setFont(new java.awt.Font("Academy Engraved LET", 0, 14));
        add(yearChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 75, -1));
        yearChoice.add("All");
        yearChoice.add("2012");
        yearChoice.add("2013");
        yearChoice.add("2014");
        yearChoice.add("2015");
        yearChoice.add("2016");
        yearChoice.add("2017");
        yearChoice.add("2018");
        yearChoice.add("2019");
        yearChoice.add("2020");
        yearChoice.add("2021");
        yearChoice.add("2022");
        yearChoice.add("2023");
        yearChoice.add("2024");

        monthChoice.setFont(new java.awt.Font("Academy Engraved LET", 0, 14));
        add(monthChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 75, -1));
        monthChoice.add("All");
        monthChoice.add("Jan");
        monthChoice.add("Feb");
        monthChoice.add("Mar");
        monthChoice.add("Apr");
        monthChoice.add("May");
        monthChoice.add("Jun");
        monthChoice.add("Jul");
        monthChoice.add("Aug");
        monthChoice.add("Sept");
        monthChoice.add("Oct");
        monthChoice.add("Nov");
        monthChoice.add("Dec");

        viewButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 71, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Total  Purchase  Amount : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, 22));

        totalPurAmt.setFont(new java.awt.Font("Tahoma", 0, 14));
        totalPurAmt.setText("O.O NRS");
        add(totalPurAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 108, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 290, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 290, 11));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("Highest Transaction Record :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 200, 22));

        highPurDay.setFont(new java.awt.Font("Tahoma", 0, 14));
        add(highPurDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 190, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        try {
            PurchaseModel pm=new PurchaseModel();
                    if("All".equals(yearChoice.getSelectedItem()))
            {
                
                if("All".equals(monthChoice.getSelectedItem()))
            {
               String resArr[]=pm.AllYearAllMonth().split(",");
               totalPurAmt.setText(resArr[0]);
               highPurDay.setText(resArr[1]);
            }
                else
                {
                String resArr[]=pm.AllYearAMonth(monthsVal.get(monthChoice.getSelectedItem()+"")+"").split(",");
               totalPurAmt.setText(resArr[0]);
               highPurDay.setText(resArr[1]);
                }
           
            }
            else { 
                if("All".equals(monthChoice.getSelectedItem()))
            {
               String resArr[]=pm.AYearAllMonth(yearChoice.getSelectedItem()+"").split(",");
               totalPurAmt.setText(resArr[0]);
               highPurDay.setText(resArr[1]);
            }
                else
                {
              String resArr[]=pm.AYearAMonth(yearChoice.getSelectedItem()+"",monthsVal.get(monthChoice.getSelectedItem())+"").split(",");
               totalPurAmt.setText(resArr[0]);
               highPurDay.setText(resArr[1]);
                }
             totalPurAmt.setVisible(false);
             totalPurAmt.setVisible(true);
             highPurDay.setVisible(false);
             highPurDay.setVisible(true);

            }
                    
                    
                    // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(purchaseDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel highPurDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable2;
    private java.awt.Choice monthChoice;
    private javax.swing.JLabel totalPurAmt;
    private javax.swing.JButton viewButton;
    private java.awt.Choice yearChoice;
    // End of variables declaration//GEN-END:variables
DefaultTableModel dft;
HashMap monthsVal;
}
